CLASS LHC_DEALPOSITION DEFINITION INHERITING FROM CL_ABAP_BEHAVIOR_HANDLER.
  PRIVATE SECTION.
    METHODS:
      CALCULATEARTICLENO FOR DETERMINE ON SAVE
        IMPORTING
          KEYS FOR  DealPosition~CalculateArticleNo .
ENDCLASS.

CLASS LHC_DEALPOSITION IMPLEMENTATION.
  METHOD CALCULATEARTICLENO.
  ENDMETHOD.
ENDCLASS.
