CLASS LHC_DEALPRICE DEFINITION INHERITING FROM CL_ABAP_BEHAVIOR_HANDLER.
  PRIVATE SECTION.
    METHODS:
      CALCULATEPRICELEVEL FOR DETERMINE ON SAVE
        IMPORTING
          KEYS FOR  DealPrice~CalculatePriceLevel .
ENDCLASS.

CLASS LHC_DEALPRICE IMPLEMENTATION.
  METHOD CALCULATEPRICELEVEL.
  ENDMETHOD.
ENDCLASS.
